tap "felixkratz/formulae"
tap "nikitabobko/tap"

brew "eza"
brew "git"
brew "htop"
brew "jq"
brew "openjdk"
brew "neovim"
brew "nvm"
brew "tmux"
brew "zsh"
brew "powerlevel10k"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zsh-autocomplete"
brew "zoxide"
brew "docker"
brew "docker-compose"
brew "mole"

# nvim
brew "ripgrep" #need for telescope nvim

# application
cask "font-0xproto-nerd-font"
cask "alt-tab"
cask "docker"
cask "google-chrome"
cask "shortcat"
cask "telegram"
cask "vlc"
cask "wezterm"
cask "visual-studio-code"
